apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-bridge-workloads-demo.fullname" . }}
  labels:
    {{- include "gitops-bridge-workloads-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.acrImage.enabled }}
    - port: {{ .Values.service.appPort }}
      targetPort: app
      protocol: TCP
      name: app
    {{- end }}
  selector:
    {{- include "gitops-bridge-workloads-demo.selectorLabels" . | nindent 4 }}
